websites:
  - matcher: apps.fujisan.co.jp/docwiki
    dateregexp: 最終更新: (\d{4}/\d{2}/\d{2} \d{2}:\d{2})
    datelayout: 2006/01/02 15:04
    timezone: Asis/Tokyo
  - matcher: apps.fujisan.co.jp/redmine
    dateregexp: title="(\d{4}\-\d{2}\-\d{2} \d{2}:\d{2})">([^<]+)</a>前に更新.
    datelayout: 2006-01-02 15:04
    timezone: Asis/Tokyo
port: 7777
