websites:
  - url_filter: apps.fujisan.co.jp/docwiki
    date_match: "最終更新: (\\d{4}/\\d{2}/\\d{2} \\d{2}:\\d{2})"
    date_layout: "2006/01/02 15:04"
    timezone: Asis/Tokyo
  - url_filter: apps.fujisan.co.jp/redmine
    date_match: "title=\"(\\d{4}\\-\\d{2}\\-\\d{2} \\d{2}:\\d{2})\">([^<]+)</a>前に更新."
    date_layout: "2006-01-02 15:04"
    timezone: Asis/Tokyo
not_modified_port: 7777
check_modified_port: 7778
update_port: 7778
db_file: store.db
